name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build, Tag, and Push Docker Image to Amazon ECR
        run: |
          docker build -t medusa-backend .
          docker tag medusa-backend:latest 430118850209.dkr.ecr.ap-south-1.amazonaws.com/medusa-backend:latest
          docker push 430118850209.dkr.ecr.ap-south-1.amazonaws.com/medusa-backend:latest

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: medusa-service
          cluster: medusa-cluster
          wait-for-service-stability: true
